clc; 

%%
% i = 1 è p_loss = 1
% i = 2 è p_loss = 0.99
% i = 3 è p_loss = 0
i = 1;

%%
% qui mettiamo il nome del simulink
sim_output = sim('Part1_FIXED.slx');

%% estrazione tag 

%funzione ternaria per tirare fuori i tag dalla simulazione
ternary_str = @(arr, s_true, s_false) subsref({s_true, s_false}, struct('type', '{}', 'subs', {{2 - (arr(1) == 0)}}));

T_s = (sim_output.tout(end)-sim_output.tout(1))/(length(sim_output.tout)-1);
env = ternary_str(sim_output.env.signals.values, 'sim', 'ros');
sim_noise_enabled = ternary_str(sim_output.sim_noise_enabled.signals.values, 'no', 'yes');
p_loss = sim_output.p_loss.signals.values(1);

% domanda, Ta e Tc come li importo????
% potrei fare direttamnete dal workspace e fregarmene

%% 
empty_struct = struct('label', [],...
                       'env', [], ...
                      'sim_noise_enabled', [], ...
                      'T_s', [], ...
                      'Ta', [], ...
                      'Tc', [], ...
                      'p_loss', [], ...
                      'q_desired', [], ...
                      'q_loc_euler', [], ...
                      'q_loc_rk2', [],...
                      'q_loc_exact', [], ...
                      'q_motion_capture', [], ...
                      'q_motion_capture_cal', [], ...
                      'gyro', [], ...
                      'acce', [], ...
                      'q_motion_capture', [], ...
                      'wheels_speed_des', [], ...
                      'wheels_speed_meas', [], ...
                      'P_filt_EKF', [], ...
                      'z_EKF', [], ...
                      'tout', [], ...
                      'out_backup', []);


%% salvataggio dati in struct 
label = 'Prova';

results = struct('label', label,...
                       'env', env, ...
                      'sim_noise_enabled', sim_noise_enabled, ...
                      'T_s', T_s, ...
                      'Ta', Ta, ...
                      'Tc', Tc, ...
                      'p_loss', p_loss, ...
                      'q_desired', q, ...
                      'q_loc_euler', sim_output.q_loc_euler, ...
                      'q_loc_rk2', sim_output.q_loc_rk2,...
                      'q_loc_exact', sim_output.q_loc_exact, ...
                      'q_motion_capture', sim_output.q_motion_capture, ...
                      'q_motion_capture_cal', sim_output.q_motion_capture_cal, ...
                      'gyro', sim_output.w_gyro, ...
                      'acce', sim_output.acce, ...
                      'wheels_speed_des', sim_output.wheels_speed_des, ...
                      'wheels_speed_meas', sim_output.wheels_speed_meas, ...
                      'P_filt_EKF', sim_output.P_filt_EKF, ...
                      'z_EKF', sim_output.z_EKF, ...
                      'tout', sim_output.tout, ...
                      'out_backup', sim_output);

%% salvataggio struct nel workspace con nome unico

nome_cartella = 'Risultati_P3';

% 2. Controlla se la cartella esiste, altrimenti creala
if ~exist(nome_cartella, 'dir')
    mkdir(nome_cartella);
end

% 3. Genera il nome dinamico del file
timestamp = datestr(now, 'yyyy-mm-dd_HHMMSS');
nome_file = sprintf('Result_%s_%s.mat', results.label, timestamp);

% 4. Crea il percorso completo (Cartella/NomeFile)
% fullfile è la funzione migliore perché gestisce bene gli slash (/ o \) 
percorso_completo = fullfile(nome_cartella, nome_file);

% 5. Salva
save(percorso_completo, 'results');

fprintf('Dati salvati in: %s\n', percorso_completo);